import random, string

amount = int(input('https://discordapp.com/gifts/rmUgF7D3XJZD0dP6
https://discordapp.com/gifts/iWCcP28sjFGGxlym
https://discordapp.com/gifts/3FyACmYqwxGsuj3M
https://discordapp.com/gifts/MjwLVonidtcDK49g
https://discordapp.com/gifts/TPCB4UpG4fI7Sdr8
https://discordapp.com/gifts/Y3ANcc6zymBiqMm3
https://discordapp.com/gifts/amhZFwWicWdbNNcr
https://discordapp.com/gifts/jIetw5VGp5zfpQYW
https://discordapp.com/gifts/F7NQmK58V9e7illX
https://discordapp.com/gifts/RlM5L4bYp73N5GoY
https://discordapp.com/gifts/ScwTPae7T2qutQNw
https://discordapp.com/gifts/vT5YKkWrCGNETFE1
https://discordapp.com/gifts/yAiPqED6EsKUxcTe
https://discordapp.com/gifts/mglhzctGYFE1c0yf
https://discordapp.com/gifts/Xw74z9PTYtleVImR
https://discordapp.com/gifts/HDHZOhzluanSmQVJ
https://discordapp.com/gifts/24rNooQg4f32mLBX
https://discordapp.com/gifts/E0cTfPX1FRDGoRaL
https://discordapp.com/gifts/xBLqKl9Q4bzZNxSF
https://discordapp.com/gifts/OBR3llZLxaKUnC0d
https://discordapp.com/gifts/jXMQkv18aFgFARxl
https://discordapp.com/gifts/n7N2c4sa1KlNPMvo
https://discordapp.com/gifts/i7f1oZqWIbJ7r1Nz
https://discordapp.com/gifts/pkAWmGuv7QoyeIth
https://discordapp.com/gifts/kEkrTLxIjnA0RXDV
https://discordapp.com/gifts/unUfc6ycfex89u14
https://discordapp.com/gifts/jBlQT3KUWavdwQO9
https://discordapp.com/gifts/TCv5rqEwnG9adqaU
https://discordapp.com/gifts/Ywaeei0laApRcpvU
https://discordapp.com/gifts/cZZ6gexClld32vrl
https://discordapp.com/gifts/v3E4RuzZPlp9Ibbn
https://discordapp.com/gifts/HRY2K1YZLS0tVLXc
https://discordapp.com/gifts/coohd3DqSewWf12S
https://discordapp.com/gifts/zmjw4uYhZP2RSiNP
https://discordapp.com/gifts/HchxfLefEjxHDc6P
https://discordapp.com/gifts/a31ApV9S4pxXbkYL
https://discordapp.com/gifts/Wj08goBfIAWpPeRN
https://discordapp.com/gifts/TyvfL2IOJjRuGNsF
https://discordapp.com/gifts/fYV31q15N0KqQZ4q
https://discordapp.com/gifts/575HdIISZ14ZMOcC
https://discordapp.com/gifts/HycHw7gQ60fhmUA1
https://discordapp.com/gifts/5hP9bNFBLuAywNl1
https://discordapp.com/gifts/TC9u4ztc2x349NX3
https://discordapp.com/gifts/MxYbpTxA5Z0FNf8j
https://discordapp.com/gifts/rTMVtWBtBQaS564H
https://discordapp.com/gifts/8ybmq7ZYDpv4d7su
https://discordapp.com/gifts/lJlPDAsyX0LtNNxr
https://discordapp.com/gifts/wqse6y9Xr8HVJvR2
https://discordapp.com/gifts/prqQDAlTtwXwL4uQ
https://discordapp.com/gifts/dktXVj0LjSjyne6u
https://discordapp.com/gifts/nrREdK6bz4uPH1ao
https://discordapp.com/gifts/D3KDwC3itLwCked8
https://discordapp.com/gifts/99qCSIJMHYtFIO7x
https://discordapp.com/gifts/aSZ6KhPIAIA3esNb
https://discordapp.com/gifts/BrkVdyZkAraQ0H0m
https://discordapp.com/gifts/Wq6ti9fe5MShjmq0
https://discordapp.com/gifts/SrVBPj8O0ddHjNZC
https://discordapp.com/gifts/XN62vWfAE8XhIGVP
https://discordapp.com/gifts/dohzFddPvwfnZnf6
https://discordapp.com/gifts/CfKoV1v1NtxAItY4
https://discordapp.com/gifts/8rsJMZAUwUMGg1B6
https://discordapp.com/gifts/zxvDdjnko28MzCic
https://discordapp.com/gifts/h7Zd3LcKRnCCkBxX
https://discordapp.com/gifts/5jTSCncHAPTLTCMp
https://discordapp.com/gifts/iTLyoAtlTg7fauiw
https://discordapp.com/gifts/kEYkLnrUic4qJV4C
https://discordapp.com/gifts/UQ62TZpoc91PGdgJ
https://discordapp.com/gifts/HjEFeCGXHF2NzBQX
https://discordapp.com/gifts/ITGIQcVCQBXViwKX
https://discordapp.com/gifts/HAoDxfmOJsUjkcF9
https://discordapp.com/gifts/CHe2i4PjKlHGqa3N
https://discordapp.com/gifts/MfDari06FmXTHXMN
https://discordapp.com/gifts/tmpdLrrsgUIvngSP
https://discordapp.com/gifts/MBSsPTvIXdxgYfXK
https://discordapp.com/gifts/KMAwRtvstuMKubZE
https://discordapp.com/gifts/5PleRCtnyh2YIBEB
https://discordapp.com/gifts/5Nxr7xxXEQqYR9r2
https://discordapp.com/gifts/lpmPcXmDezazPiXc
https://discordapp.com/gifts/gXoKJlF33H49f6cW
https://discordapp.com/gifts/cL0bhHRx9qdn7Vth
https://discordapp.com/gifts/6ck4zg3zyzoOupHt
https://discordapp.com/gifts/XKVxljy6ubNmF4uo
https://discordapp.com/gifts/hm3eg5usI9M5GeLd
https://discordapp.com/gifts/NVyyCRP9pNlLBpQN
https://discordapp.com/gifts/KPdYdinKIgWHSbr1
https://discordapp.com/gifts/vAyrlSgZvR3TY6cN
https://discordapp.com/gifts/asUYnbkpWGaFe93L
https://discordapp.com/gifts/onyWHhxb74Fa3Zls
https://discordapp.com/gifts/UJbCoWwyBj3Y5L1G
https://discordapp.com/gifts/iC584QGCYAoRaitR
https://discordapp.com/gifts/pH8AkLdOUDDSOYlw
https://discordapp.com/gifts/UqaiO7TIBvPzzr3J
https://discordapp.com/gifts/0plVHAOWJcueRoIY
https://discordapp.com/gifts/HddaedKEjYQ2FJ0O
https://discordapp.com/gifts/1Um48LNx2NfdDkFh
https://discordapp.com/gifts/29BoumB1qNZKW29U
https://discordapp.com/gifts/wJ0AYVBLhZGTNEn2
https://discordapp.com/gifts/qjqdh9zo2zQyzjkx
https://discordapp.com/gifts/RphKp0V6yYBKldrO
https://discordapp.com/gifts/1Q9PUzqzNz36j1hq
https://discordapp.com/gifts/58Znm7ENFVNa0nIR
https://discordapp.com/gifts/lAjy5QJv059Sxo7M
https://discordapp.com/gifts/5l1HxZjAdhuulVpl
https://discordapp.com/gifts/KoAXV7sWq89S6VkV
https://discordapp.com/gifts/e4GsVH5FbsWr375C
https://discordapp.com/gifts/zmqPTCAY3Obf4kIg
https://discordapp.com/gifts/x92y0eiieRq2KZti
https://discordapp.com/gifts/HKnvpxqJzXAmApv7
https://discordapp.com/gifts/F9r5EpYGnGeSLoyY
https://discordapp.com/gifts/QNd7ZzUXVtth3Pji
https://discordapp.com/gifts/BfLWqbmQYxtEg47i
https://discordapp.com/gifts/vVwYxG8b1zkKwp6I
https://discordapp.com/gifts/VULWfEklG6gDnfuT
https://discordapp.com/gifts/ZCRgxfCmQGge14Bd
https://discordapp.com/gifts/VsyTvdQVc2Jdxjgk
https://discordapp.com/gifts/z0i2CFqfLKtSSmhQ
https://discordapp.com/gifts/HrGetJvXOVFOrUJV
https://discordapp.com/gifts/l8d6EGL5imtBjSpn
https://discordapp.com/gifts/E6xKzdmofM8JN0Dp
https://discordapp.com/gifts/bYewCnP59UDsOZO4
https://discordapp.com/gifts/6JxwFDngSsFF5a8k
https://discordapp.com/gifts/oHwm62bs29vWv3lR
https://discordapp.com/gifts/zGs2KuXaQaodrkaK
https://discordapp.com/gifts/lrG6mUiyyz0DvWaO
https://discordapp.com/gifts/8d0H90Uqek2ntcqs
https://discordapp.com/gifts/7LmGQShH0UVYl0th
https://discordapp.com/gifts/VqDjIefleJTZplpi
https://discordapp.com/gifts/XvUoeVu3ewOZ9xnQ
https://discordapp.com/gifts/y3k1qCnwICDgIniy
https://discordapp.com/gifts/T6wkPd0aVtbl2kKN
https://discordapp.com/gifts/rgfJYXpkLoWhOzAG
https://discordapp.com/gifts/fAwD95cvGkZZYD4p
https://discordapp.com/gifts/iJ3bviit8PUYxqAO
https://discordapp.com/gifts/wlF2rCUhnsU68ABO
https://discordapp.com/gifts/OKAOqzN7W5EEItTr
https://discordapp.com/gifts/Byba4Q4spsbn7ppg
https://discordapp.com/gifts/T6zazQ7EH2d2pXDI
https://discordapp.com/gifts/Zz1oKwMcQBxxaOGu
https://discordapp.com/gifts/rQBrHxd2eWucdo3r
https://discordapp.com/gifts/I35uWiX2AnwwhVzw
https://discordapp.com/gifts/35yVaVbG6m55wh1g
https://discordapp.com/gifts/STmXj6IwOD8xxtxo
https://discordapp.com/gifts/AXy2AmWaknZvDfVU
https://discordapp.com/gifts/LoBUJvEFJ8QcXlI8
https://discordapp.com/gifts/85reTebkMq9zHCq5
https://discordapp.com/gifts/T9BPPIAeSJQDYvJf
https://discordapp.com/gifts/3FaO3o3X3Q2AE3PV
https://discordapp.com/gifts/smJjUBrn3UaRh28P
https://discordapp.com/gifts/VepACLObtL0tlWI0
https://discordapp.com/gifts/Y8zxpvgDlmCBVEgh
https://discordapp.com/gifts/fSfCDRIG985NoO90
https://discordapp.com/gifts/3iXcTLDSikIG2KPM
https://discordapp.com/gifts/wi7Iewx7XWx10qrm
https://discordapp.com/gifts/Sl7ZHLy0XGXgmFPG
https://discordapp.com/gifts/7trqaotlvXLUM8AP
https://discordapp.com/gifts/VG7zfSb0wH91AACr
https://discordapp.com/gifts/PbPuTqjgGwX2qLZh
https://discordapp.com/gifts/EWUyv9SV6BxGGjFr
https://discordapp.com/gifts/P2PawJvCAZxHyCJD
https://discordapp.com/gifts/t10ORQVkdr1mN8ZB
https://discordapp.com/gifts/bFKveqmGgqojlXvb
https://discordapp.com/gifts/wmkakwerltX9AMp3
https://discordapp.com/gifts/oGfl4oI6BTf9KsJd
https://discordapp.com/gifts/yzZMYjot6hvL0V7o
https://discordapp.com/gifts/3s1m9phju5rbFGD0
https://discordapp.com/gifts/hdxZ7oATUbhc0hhK
https://discordapp.com/gifts/Wmr6fsnTNXHg9ByU
https://discordapp.com/gifts/97CXi7J4H3VmhX9F
https://discordapp.com/gifts/SnxzsBgWFn3hMoDc
https://discordapp.com/gifts/theXeWuZa1GtXq8g
https://discordapp.com/gifts/Wu2ZPR6DkKGENJwl
https://discordapp.com/gifts/c3WGdhM7FYrpxG2l
https://discordapp.com/gifts/Y9LJ6ecYO4NgUT2C
https://discordapp.com/gifts/zzDd1bgrIAuV6qg9
https://discordapp.com/gifts/73BMgOF0yL3XXQaB
https://discordapp.com/gifts/bpDzt1BokHbZw2dK
https://discordapp.com/gifts/og7zVnWBvGx0ZI1g
https://discordapp.com/gifts/qZt3fzQqDqCu8BUg
https://discordapp.com/gifts/eIerNI1y3MRrf219
https://discordapp.com/gifts/pGhzSfjflGhrBb1w
https://discordapp.com/gifts/rqMDD5jMtHAOWvxg
https://discordapp.com/gifts/ZBVs0dxDKFMJJoTZ
https://discordapp.com/gifts/7SmPsYvfs1tAaDkF
https://discordapp.com/gifts/NchrElwmcAjIEXhR
https://discordapp.com/gifts/7Iyz8HKUDMVdoBy0
https://discordapp.com/gifts/SWct1EvMQ7ClOUh2
https://discordapp.com/gifts/q5EkGDTo4V0bVrwj
https://discordapp.com/gifts/wyp9nL9HRu253AdW
https://discordapp.com/gifts/QPxjNHq4xHyJPRjH
https://discordapp.com/gifts/mWU3Yadt2voxTE1U
https://discordapp.com/gifts/HZsY6mbaqs37fQA4
https://discordapp.com/gifts/e2a9TnoQuKXhItMt
https://discordapp.com/gifts/OrRlJGpQ8TiWQouA
https://discordapp.com/gifts/fzjVKjyvCGP0CucI
https://discordapp.com/gifts/53ZTRmHYKhqjPtgY
https://discordapp.com/gifts/lsOoEIJnmnkcpAZc
https://discordapp.com/gifts/rWasE0lLScKRXROs
https://discordapp.com/gifts/PPZndf9JkdCOjIWq
https://discordapp.com/gifts/AjEwaxDDgR0haoVY
https://discordapp.com/gifts/T5F0fDnvbppqQ8B8
https://discordapp.com/gifts/i4HdZgFe8gwOBrWU
https://discordapp.com/gifts/O8zHGjROJDxkz2zY
https://discordapp.com/gifts/4dSydveI12LBkvdV
https://discordapp.com/gifts/YOTk0dG9uyI6UJDH
https://discordapp.com/gifts/Wvx0se2ebHAqvzi7
https://discordapp.com/gifts/vLIMKRqdBO2rOIt5
https://discordapp.com/gifts/XenDW7wakMphEF1r
https://discordapp.com/gifts/qCvtVEABe8cZ5Fut
https://discordapp.com/gifts/UnEJraCLF9tFQS38
https://discordapp.com/gifts/yFds9KuRCfVHZgpw
https://discordapp.com/gifts/LV6sOpJ4p69KkauE
https://discordapp.com/gifts/V0cijNHWKfy4rQ4U
https://discordapp.com/gifts/5Fov7fLk8iIWoeOC
https://discordapp.com/gifts/L8YCjjweZaRm00uc
https://discordapp.com/gifts/0G3jJqpxAyJdfYdh
https://discordapp.com/gifts/bSM495L7sA2TkS93
https://discordapp.com/gifts/7dfAOyzcNKRv6lsS
https://discordapp.com/gifts/D4YsLWLWxth0dkp4
https://discordapp.com/gifts/5q70L5o4dJlm5E8O
https://discordapp.com/gifts/S1nCA6n285bQ5ZlW
https://discordapp.com/gifts/OJTuqhahQNOb6470
https://discordapp.com/gifts/VDQ7ChWNoncjebpn
https://discordapp.com/gifts/Y3bsXoXE6AMqvL06
https://discordapp.com/gifts/pJMKzV1ahT0s6F6j
https://discordapp.com/gifts/xxCj9hoxAHMR9kMy
https://discordapp.com/gifts/wb312rLPlqrU1ulF
https://discordapp.com/gifts/xPQXTLGnO4fvvSnR
https://discordapp.com/gifts/wnqD1BNELPeSl0Tg
https://discordapp.com/gifts/jHQrv8bA0Zg6agES
https://discordapp.com/gifts/EBl8RPLHnPdmqR2J
https://discordapp.com/gifts/13BuOxnyFBAQ9xp1
https://discordapp.com/gifts/fsOyr5JweMF8jyWb
https://discordapp.com/gifts/196SlRhilMr007gB
https://discordapp.com/gifts/ldB5Y2bubtQKPuCa
https://discordapp.com/gifts/VZzzafdkvBzEPJIx
https://discordapp.com/gifts/LRGGAUVeU4v3toYL
https://discordapp.com/gifts/1JqECXfy4Ab1OpFv
https://discordapp.com/gifts/6LSQqv26Gcdmom41
https://discordapp.com/gifts/RKoK31qao0zXA0u7
https://discordapp.com/gifts/DlD44jki09mZ741j
https://discordapp.com/gifts/TWuDuI2OIWghB2jN
https://discordapp.com/gifts/ML6wN94QQ1Z1tCTv
https://discordapp.com/gifts/G3RiNpIGbtszBdHE
https://discordapp.com/gifts/fF2FSijYqrhxt1W3
https://discordapp.com/gifts/VtveLohigTnfpyH3
https://discordapp.com/gifts/AtRJSq0mc4oBuiuJ
https://discordapp.com/gifts/1qaNBjAf4VFLiZuM
https://discordapp.com/gifts/8orKUiROcuqWQXfA
https://discordapp.com/gifts/MhB8E6jpxSu6NRh1
https://discordapp.com/gifts/n3FHZcw97Y0c52CM
https://discordapp.com/gifts/O09SzWlimGduiQx5
https://discordapp.com/gifts/kWiG7RoKMMoBKSEZ
https://discordapp.com/gifts/ejIvEWH6qCOt3UQL
https://discordapp.com/gifts/Dbn2CCKkoe0QIp9k
https://discordapp.com/gifts/x3wPs1w6IfxYCPlv
https://discordapp.com/gifts/IoQyR5GV2tSQEDWw
https://discordapp.com/gifts/O3zwZfo37fMw9pxX
https://discordapp.com/gifts/031e1ZRTWXo5I2Tp
https://discordapp.com/gifts/x3Y71oOIfN8e0qVv
https://discordapp.com/gifts/ihwNRZ5pTaOoZ7oL
https://discordapp.com/gifts/7ykgBwMpmK226mi3
https://discordapp.com/gifts/pe8otQyLYavKOkNk
https://discordapp.com/gifts/9uIvX8WdJkZv4BMb
https://discordapp.com/gifts/I6W5lgF0DId8NKGA
https://discordapp.com/gifts/fwA3MnlENp3a9dI1
https://discordapp.com/gifts/ZUI4iYge3vfrL384
https://discordapp.com/gifts/ozdI2nCNkB15d18l
https://discordapp.com/gifts/jUj9mSzJOsgH3Xs4
https://discordapp.com/gifts/9u40nfrzivEm0bpK
https://discordapp.com/gifts/Q0yrHpM7OBScuAPb
https://discordapp.com/gifts/1haZLwDqJDLZ65UI
https://discordapp.com/gifts/N2IMsoODSjCI3Yga
https://discordapp.com/gifts/YiWntCcrbSyPSfS7
https://discordapp.com/gifts/3k7kOJR0WQLnW8BA
https://discordapp.com/gifts/BXD8lZTGDR745Ee9
https://discordapp.com/gifts/8kt1pGifwWOU6Mqf
https://discordapp.com/gifts/oTGmL1OA4CwIVVlO
https://discordapp.com/gifts/a1CPm3ADQ0mpqxz4
https://discordapp.com/gifts/SfSQEKYdaDyUyBXX
https://discordapp.com/gifts/kdFXAkHms4LiwY7r
https://discordapp.com/gifts/5GsOHvQllHjVBzgp
https://discordapp.com/gifts/uvd3wRRUvOHlMbyi
https://discordapp.com/gifts/fnc3o4gl20hLYnHm
https://discordapp.com/gifts/lBwqCzOWtRe3W8Ha
https://discordapp.com/gifts/JveJ1KU2cp8XFbBW
https://discordapp.com/gifts/iH96WjzeJjYCgHcT
https://discordapp.com/gifts/5yA4B25qlnKnUiR4
https://discordapp.com/gifts/6Lzppu3tB4A4z78g
https://discordapp.com/gifts/A9FogbIKxmkn9Xme
https://discordapp.com/gifts/YgBgYOfpzXZQwnF6
https://discordapp.com/gifts/5j7rWHIBqalSXbjB
https://discordapp.com/gifts/9W34Flt5tpVaxIBq
https://discordapp.com/gifts/hb1DdoysDWYrh9zf
https://discordapp.com/gifts/0JUL2Axvcz3BTtNa
https://discordapp.com/gifts/UT0SgAqClBbtUECr
https://discordapp.com/gifts/bkjJUqzhHJhYd5Sb
https://discordapp.com/gifts/xnjxK4qVxH80Telw
https://discordapp.com/gifts/UF97DoPkipqTtMQV
https://discordapp.com/gifts/xalfWzoOzYU4YG6c
https://discordapp.com/gifts/gRXp6yQt2TleCKvE
https://discordapp.com/gifts/VCmxaNSEnlkQVagB
https://discordapp.com/gifts/eY60avVrIu9tVk1z
https://discordapp.com/gifts/nNpZGGZDBxGD7wB1
https://discordapp.com/gifts/7B1dY5TkhCZCybct
https://discordapp.com/gifts/3hj1D27U2o7hn7IE
https://discordapp.com/gifts/3FGNEIv2tVOFyOuX
https://discordapp.com/gifts/F8uCY00o1pcCz4oW
https://discordapp.com/gifts/697q4MEvaBmkByVo
https://discordapp.com/gifts/RNZyYPZBANjZMs0y
https://discordapp.com/gifts/KCrvm1FWvUq6awTn
https://discordapp.com/gifts/hKYCmEN92zyMhGwC
https://discordapp.com/gifts/OoYuT46HZLW8YWal
https://discordapp.com/gifts/Oydm5RHfPYCYzaq0
https://discordapp.com/gifts/nedfdjHRayhBu0yv
https://discordapp.com/gifts/HNLBuid63a5DUCMt
https://discordapp.com/gifts/bzx8taCGERAXtLGh
https://discordapp.com/gifts/6TF06xlMENfQpY3k
https://discordapp.com/gifts/Mh3nPgJRb08PzoEi
https://discordapp.com/gifts/nzOk6eGASB7m1idr
https://discordapp.com/gifts/woqAikfazGoTsmkT
https://discordapp.com/gifts/oN2xIeRNRXFVb4Wi
https://discordapp.com/gifts/P5J1SzWBpKqpoOwB
https://discordapp.com/gifts/AJPSwXXlZt9EPdYw
https://discordapp.com/gifts/Bwqji2P2hUInoZis
https://discordapp.com/gifts/ZeoonkDHy2VuZOl4
https://discordapp.com/gifts/n1kXy0N4UGQtBKPx
https://discordapp.com/gifts/GLjNR9zuKpdK1taN
https://discordapp.com/gifts/BSrZoApWni3vRGzp
https://discordapp.com/gifts/3cZHoEPe9eiwsojI
https://discordapp.com/gifts/M1BOrwrjsuy3eIHd
https://discordapp.com/gifts/IA7waiDq0j8Wg8SL
https://discordapp.com/gifts/djHZBAjgGFE9MAKC
https://discordapp.com/gifts/VohE72Nqr2Awjvwj
https://discordapp.com/gifts/8nIfTtdoVLKptDJb
https://discordapp.com/gifts/XEUEB7gP96PrTssQ
https://discordapp.com/gifts/EwloXmuKuqyFZ284
https://discordapp.com/gifts/RzFM6yu0OdkTcIyT
https://discordapp.com/gifts/XYjHmq8PYXMEVovq
https://discordapp.com/gifts/WHrAgmykEuXscipD
https://discordapp.com/gifts/GbpS0R6IbV4aDzL7
https://discordapp.com/gifts/38t585ZEeYK5KOXy
https://discordapp.com/gifts/lkovWLBllpPBmwal
https://discordapp.com/gifts/aEKnTW7fqHdoGN2w
https://discordapp.com/gifts/ktn927oFqB60f76m
https://discordapp.com/gifts/1E4kBBmuQIHEU9eQ
https://discordapp.com/gifts/DPDJClA5ckjZb05o
https://discordapp.com/gifts/MRwILJKvcJAuLT9H
https://discordapp.com/gifts/KlSgyZthtsPKrgfa
https://discordapp.com/gifts/ZCwYWgXRAL83SvID
https://discordapp.com/gifts/H0jjOBFE70uoNHBz
https://discordapp.com/gifts/qSLzPIe33CKBbGfO
https://discordapp.com/gifts/uWRuDFNqPKmfIlIJ
https://discordapp.com/gifts/or6yMgmGPcK6Mb3y
https://discordapp.com/gifts/Wnvub1RLU9N36Lgm
https://discordapp.com/gifts/Y1Y5X84XNBaq2Kur
https://discordapp.com/gifts/P9MpNiObUVTMW6Fe
https://discordapp.com/gifts/i9MUeWF5ULbCYuIH
https://discordapp.com/gifts/OXmJYpHzTdXjswWz
https://discordapp.com/gifts/vxGjwo5KU1pjbk3m
https://discordapp.com/gifts/PXXSFxxQ7DJi4Klu
https://discordapp.com/gifts/bh3wpXN3SPG3mr6f
https://discordapp.com/gifts/68rpoAX2qVVFYJoF
https://discordapp.com/gifts/fH25XHKqyYEVdQRc
https://discordapp.com/gifts/jIFD7xTnAP4y6IxQ
https://discordapp.com/gifts/vh15yBtei9tRTkdR
https://discordapp.com/gifts/33UdEhq1HEJjqSfI
https://discordapp.com/gifts/KPOYo28C0wewoJ80
https://discordapp.com/gifts/Ok1KeqKt188GgNau
https://discordapp.com/gifts/sIG084ECACVw8qNo
https://discordapp.com/gifts/rnpEItZRpEM85jzi
https://discordapp.com/gifts/7EW7g9ita0dgVRO9
https://discordapp.com/gifts/o0A8i5G5NAVYRS5O
https://discordapp.com/gifts/WcarMh2ItdAWxKcx
https://discordapp.com/gifts/6EruL49cyeQYwNOa
https://discordapp.com/gifts/re0SBw6Em4gOnoin
https://discordapp.com/gifts/68gxux9RBpJ3QLRh
https://discordapp.com/gifts/IMwVS8GuDOWJOxLA
https://discordapp.com/gifts/yK6U7GdL7e0GYJ3w
https://discordapp.com/gifts/sZNyOhy4TMnhzrE1
https://discordapp.com/gifts/ejabXKmN1Uca1OQn
https://discordapp.com/gifts/vEQJ07fWduIv1uRk
https://discordapp.com/gifts/6gBHe6aAWHS3MBVB
https://discordapp.com/gifts/yg5sBu1eRhS4XYgm
https://discordapp.com/gifts/zg0Dqyyjqvt0jMph
https://discordapp.com/gifts/HhpFBo071t8T46xl
https://discordapp.com/gifts/QOMT1gIr78RIHu4o
https://discordapp.com/gifts/Ktr14qK53ZrxApLA
https://discordapp.com/gifts/STIRjUnM5YVUzzPJ
https://discordapp.com/gifts/U1I1IFLqpLBHt43j
https://discordapp.com/gifts/wQFdx3FsrQmikIJB
https://discordapp.com/gifts/XyT38jp7IFsFkBTF
https://discordapp.com/gifts/PGV6pxL7eDGIoIkD
https://discordapp.com/gifts/fc5ynBCP3t1er7pU
https://discordapp.com/gifts/6E4o72gzDktBUKfL
https://discordapp.com/gifts/eOqVet9T5NdV1jZk
https://discordapp.com/gifts/rchla0Mscnan8d1U
https://discordapp.com/gifts/AgvZamGNDQik82Qq
https://discordapp.com/gifts/aknP0a9fEYzWNXpt
https://discordapp.com/gifts/acqfBWkLOAMvSH3q
https://discordapp.com/gifts/WkljEsccrF6VXjAa
https://discordapp.com/gifts/dw8oUHJlu4BFaBzJ
https://discordapp.com/gifts/Vz1WFnuiIZ0ASrJp
https://discordapp.com/gifts/vlCZtoJRmxj6blv9
https://discordapp.com/gifts/P0K62CX8MXkZi0I2
https://discordapp.com/gifts/IgynTNQF6iIXAYXJ
https://discordapp.com/gifts/LAgSOEIqIsc1ziSP
https://discordapp.com/gifts/fkDSoim4N6cfPaBN
https://discordapp.com/gifts/QUKUTVx3SVqsbMkk
https://discordapp.com/gifts/QtV8HprQBcC2X17V
https://discordapp.com/gifts/AovtEgXsJBC8OIWP
https://discordapp.com/gifts/XLuPw1OY0m2hIJ2p
https://discordapp.com/gifts/LcG6JPxlHYhCYf2k
https://discordapp.com/gifts/UBfsiqa200RY70sB
https://discordapp.com/gifts/kGaE4dSRwhPG6KOp
https://discordapp.com/gifts/Ie1Fb8a3WRMnLGRw
https://discordapp.com/gifts/xDTSY7OIY0iWHA7l
https://discordapp.com/gifts/5EIQN5zAE6o2Tx01
https://discordapp.com/gifts/2Biy0mIelLzuyMeA
https://discordapp.com/gifts/lMvjo4l8MBhEmmms
https://discordapp.com/gifts/Rvn6Gy0swjWDVGDU
https://discordapp.com/gifts/QxSsvK15mcYP70Ka
https://discordapp.com/gifts/UxCujnD7izzyNX14
https://discordapp.com/gifts/qA43rspw7OKuuT9s
https://discordapp.com/gifts/3ATn7bJJqGvklEcL
https://discordapp.com/gifts/UAwDFjHCtT41GvbO
https://discordapp.com/gifts/frlUVGZQ54c1fvE1
https://discordapp.com/gifts/RN0tVOj5lU3pz5Jt
https://discordapp.com/gifts/7f0eh3cWnnOzBCcS
https://discordapp.com/gifts/RrFM1i6hcTaRclmk
https://discordapp.com/gifts/mnvYyH85yzdDFx4r
https://discordapp.com/gifts/voRAPsLhNBgHW1e5
https://discordapp.com/gifts/HZ78yC5VP2HOgmFr
https://discordapp.com/gifts/V3kzD7SQK456XHQu
https://discordapp.com/gifts/e8026vUE1OC7os72
https://discordapp.com/gifts/s8HTOk6ksEPBjtXa
https://discordapp.com/gifts/tGcrs6O6ZVkIJSs9
https://discordapp.com/gifts/hkKYvQowVKn7xpZ2
https://discordapp.com/gifts/VUyzAXr0wQ8bQkUD
https://discordapp.com/gifts/LvHB5kYkFzq1dSgo
https://discordapp.com/gifts/s6Xq7odhvFNFFEUe
https://discordapp.com/gifts/axXDVgIyo1Ti40ID
https://discordapp.com/gifts/ajYSpF3iRLZnsEuJ
https://discordapp.com/gifts/XBrqPVg994eheb0l
https://discordapp.com/gifts/J5JGuLBk2zQ7GVEn
https://discordapp.com/gifts/s4BeQRSkHYCxfLms
https://discordapp.com/gifts/hW2317BhBlKzYhMo
https://discordapp.com/gifts/1Ggx9Qtvf6OOiUR5
https://discordapp.com/gifts/x0Kqvu35vM7qSo7k
https://discordapp.com/gifts/50NXxrqlNw9UzF7v
https://discordapp.com/gifts/PQVwR467dvu7gCwr
https://discordapp.com/gifts/g9EQeou7qnvWIECm
https://discordapp.com/gifts/6JW0n0pEx3fzPwz0
https://discordapp.com/gifts/z3Ag5rbJHDDQZF0J
https://discordapp.com/gifts/WcxGFGrfySBTFDAV
https://discordapp.com/gifts/8lnTciYEKyAke1Tk
https://discordapp.com/gifts/aPiLNYafLWcZngH7
https://discordapp.com/gifts/4BAVku85uLbkpcBH
https://discordapp.com/gifts/Lk4ufI0NtaVvFUze
https://discordapp.com/gifts/GInxAe5O56Y0vtOr
https://discordapp.com/gifts/el8hyLD9ie5mZ5xb
https://discordapp.com/gifts/wIt2IDUCZlj46Klv
https://discordapp.com/gifts/5GFHEp2q16qMSdAO
https://discordapp.com/gifts/hoj8X5Z2ByKREnUk
https://discordapp.com/gifts/bzgK3bNAsN6EOYx5
https://discordapp.com/gifts/TZXOLhGvUbtzTBuP
https://discordapp.com/gifts/1L0YC96lk8JkHnX7
https://discordapp.com/gifts/hHPdQ5Oiwyv8gnss
https://discordapp.com/gifts/SNE6RsYvUHWwqFtL
https://discordapp.com/gifts/H5FQoS80sZUvIPcs
https://discordapp.com/gifts/XWrYVIjrPc2k0sMw
https://discordapp.com/gifts/mK3QSNlhAUL2Damr
https://discordapp.com/gifts/a5Z8pw5ZQEreAiSQ
https://discordapp.com/gifts/qK64YatMqUBgcI69
https://discordapp.com/gifts/FiAVY9I1u3vNSxfs
https://discordapp.com/gifts/xPzoLHJdVXLQ92VV
https://discordapp.com/gifts/WvhTTKdgC4LTPRcV
https://discordapp.com/gifts/nLMNvYsOrOlEhytr
https://discordapp.com/gifts/oYAFC22yfPtgB5xN
https://discordapp.com/gifts/1OrxHqzlprVJvQCE
https://discordapp.com/gifts/l56fyYVVLoi4DJ3n
https://discordapp.com/gifts/3TYXIVZJuyNKfbnY
https://discordapp.com/gifts/R7ZURgf9utxgzhCw
https://discordapp.com/gifts/PKJ6ByHGFfsVWbtG
https://discordapp.com/gifts/K0sF38dFiDrkeuJo
https://discordapp.com/gifts/xt46FyfsUT0yCvBk
https://discordapp.com/gifts/QsETbjgwStNT4lOn
https://discordapp.com/gifts/WZiotUd5OQQbR4bP
https://discordapp.com/gifts/7IgaGDWoCiVD8oo2
https://discordapp.com/gifts/UZjzYhBMcygwXl7M
https://discordapp.com/gifts/QFcEmdIz7zA03bQ4
https://discordapp.com/gifts/yXmHTF1Of1Jw3LCY
https://discordapp.com/gifts/Rakuox03eqAHWckZ
https://discordapp.com/gifts/fXKcwvp5bEtaZoxG
https://discordapp.com/gifts/4LBOWaJsOPNImW10
https://discordapp.com/gifts/GJAdk66cc7IU8oVl
https://discordapp.com/gifts/1MsEq4V2iOBYjDoF
https://discordapp.com/gifts/p5yvRrIX9xK9f1yq
https://discordapp.com/gifts/mucO1t7v9Wn5yHI2
https://discordapp.com/gifts/QGQNxQEDRyjeIwT4
https://discordapp.com/gifts/PDDWelLan4sttH9O
https://discordapp.com/gifts/q21ftMoepffoVRlE
https://discordapp.com/gifts/LWrEvEEQKOj0dToT
https://discordapp.com/gifts/CWQDOoIHGoDx9jM3
https://discordapp.com/gifts/y4yf0z0U5hbWQEqc
https://discordapp.com/gifts/Fu8TLp5z7MPWdtGv
https://discordapp.com/gifts/JPoUKwk3kFdePNQe
https://discordapp.com/gifts/sH6md7soI6QvTJvr
https://discordapp.com/gifts/RTFX1GZI0w45KQ8b
https://discordapp.com/gifts/tAYmmgbEYUNNQKFe
https://discordapp.com/gifts/G3lOfuEA11T4245H
https://discordapp.com/gifts/xQhJSpGFeQAAKFzE
https://discordapp.com/gifts/oErOur8pGe4Nay86
https://discordapp.com/gifts/aQOcZCXnneN1DspM
https://discordapp.com/gifts/UeD2X7HwFXdhFxbh
https://discordapp.com/gifts/i7FWfMgXvWL67GmR
https://discordapp.com/gifts/L6NtQaiTTXQeFKxE
https://discordapp.com/gifts/GeQ23O9MYpfBTs7U
https://discordapp.com/gifts/DubEMPnk1TahMoAu
https://discordapp.com/gifts/RYVBgYEzHTMQITJx
https://discordapp.com/gifts/fksg5liIQKeyJvST
https://discordapp.com/gifts/vnpGjvYe8wflLVrI
https://discordapp.com/gifts/2O0xkCPvqLH1JYWZ
https://discordapp.com/gifts/lU0TAYmucMFA2koD
https://discordapp.com/gifts/7gYVwGtlFrTASz9C
https://discordapp.com/gifts/brKeqwwjRuA6Hnmy
https://discordapp.com/gifts/cV30VlQhDMchCHz7
https://discordapp.com/gifts/bAdLQmPzbDxn9hgl
https://discordapp.com/gifts/fI2m8druoJbAax8Q
https://discordapp.com/gifts/zQuGE5psxpfxjuLG
https://discordapp.com/gifts/jwENKp0UIBcqEZua
https://discordapp.com/gifts/d0Iltq8XH3H1FkMX
https://discordapp.com/gifts/XgX3JIvUODOOWqXQ
https://discordapp.com/gifts/XP9CqVbFRet4vB3s
https://discordapp.com/gifts/IjEGARHVARRNh5nh
https://discordapp.com/gifts/wBDQqXXvSN2emSW8
https://discordapp.com/gifts/sibPncEBXgU6ZyNH
https://discordapp.com/gifts/2geyGA2zMkd9TLcT
https://discordapp.com/gifts/aH2NE1WUFyZ1bk3s
https://discordapp.com/gifts/YNGDMG1GrxqG4nBi
https://discordapp.com/gifts/1YhUH0QPZ5PqXloT
https://discordapp.com/gifts/JJT6gpe5QXRm8Pv7
https://discordapp.com/gifts/dExv8I1Jjkl231nN
https://discordapp.com/gifts/VnMcjNUXrhIjSVzF
https://discordapp.com/gifts/1WVxrHAJoIqq8jym
https://discordapp.com/gifts/No6GAfgGgWFZhfbL
https://discordapp.com/gifts/tia7NGS9fwKWXqek
https://discordapp.com/gifts/sGCkwv7xfNsek7k4
https://discordapp.com/gifts/FFBReA3NQhws99qn
https://discordapp.com/gifts/vLSwX2ac1wIwIIXC
https://discordapp.com/gifts/1s8vKqUnMLFGt0Zx
https://discordapp.com/gifts/dHMHunoOnzJagshJ
https://discordapp.com/gifts/UKL8W3tt6yy0GYI7
https://discordapp.com/gifts/XeeXQcHgU0uUIlts
https://discordapp.com/gifts/UCx3MSnLT3KyLYIv
https://discordapp.com/gifts/6bRUKMrL3WLB45XJ
https://discordapp.com/gifts/kc7Yp3GMSz2j1rzP
https://discordapp.com/gifts/cZmogLBWXG1FwxMs
https://discordapp.com/gifts/YEutto0OpR4G2xZZ
https://discordapp.com/gifts/5YZSMAwuUOKrfN8A
https://discordapp.com/gifts/LAHZb9qFkrasxzqD
https://discordapp.com/gifts/CAybNep1yDkIXY23
https://discordapp.com/gifts/lYylgiVrZ6NE5cwT
https://discordapp.com/gifts/tntmKeXZMdCYcYlL
https://discordapp.com/gifts/J041A9zO2Fh3tlva
https://discordapp.com/gifts/eelxIGwCI7sacxox
https://discordapp.com/gifts/Zh2EsRmAvvmUXzxx
https://discordapp.com/gifts/UuJ2dP0XTgHArpEn
https://discordapp.com/gifts/AJqccngovEPFiOH0
https://discordapp.com/gifts/lzGAOp1eefhjZ4D1
https://discordapp.com/gifts/BSqtaGSpnn8GNGCb
https://discordapp.com/gifts/GMSS8ktiYbbibl0M
https://discordapp.com/gifts/52PXNuLRqgOgiTjg
https://discordapp.com/gifts/s1Qemg21kUEOeUjx
https://discordapp.com/gifts/nqk0iGoyg4KnfMys
https://discordapp.com/gifts/MonvespXS6vLZA5v
https://discordapp.com/gifts/ZNZkDk2g5868aBWT
https://discordapp.com/gifts/drmukCNvlnn8VXyJ
https://discordapp.com/gifts/iI2N9axjQCl6yoi4
https://discordapp.com/gifts/uitTf5m8qQ6Df1aJ
https://discordapp.com/gifts/95Tyf5O2EdmwTxWl
https://discordapp.com/gifts/pHPqcKD4qWE5S0gK
https://discordapp.com/gifts/zouuhLpBlmRnNoEz
https://discordapp.com/gifts/VqnaaCx1KKKJXUnZ
https://discordapp.com/gifts/LypPTy3YaPrfXmpi
https://discordapp.com/gifts/FEOQsZ3rFcr2cpzo
https://discordapp.com/gifts/o85zrNm7Y40SU8kK
https://discordapp.com/gifts/aajPCW5kTyajOx3D
https://discordapp.com/gifts/RnHvynGg93Bw5T7I
https://discordapp.com/gifts/Sr3MKClU2FpSHqpR
https://discordapp.com/gifts/BRMOnR2MsamsPvld
https://discordapp.com/gifts/yMhIT6ohprv928cg
https://discordapp.com/gifts/s4TcnBeboiADQGx1
https://discordapp.com/gifts/43MRTM1Azuw1ULpp
https://discordapp.com/gifts/kh9gXdMKyi29U3td
https://discordapp.com/gifts/j5UPGBhm8DI03KHj
https://discordapp.com/gifts/azf4bS32r1WAnhx9
https://discordapp.com/gifts/k61ubWZQ3s2kPjEU
https://discordapp.com/gifts/afuYo35hApDkKCCw
https://discordapp.com/gifts/M6ukiT83lFE8tKDt
https://discordapp.com/gifts/qJGHOr1oxsfT5cKR
https://discordapp.com/gifts/NmQLczDowBhEtuEv
https://discordapp.com/gifts/8wabGYtynyQU8Q9B
https://discordapp.com/gifts/hn0YDdNcyPYNr6hJ
https://discordapp.com/gifts/A2GMuiovLCVW4elc
https://discordapp.com/gifts/yNpGN3HPKIwSH4i6
https://discordapp.com/gifts/1Bo84AE3oliOZqV6
https://discordapp.com/gifts/LYJ2tPggk4yyzQDE
https://discordapp.com/gifts/bsTyPON1i1ajONP1
https://discordapp.com/gifts/quQjExuq4eg5x1ol
https://discordapp.com/gifts/efWT5vmpUKMEXecZ
https://discordapp.com/gifts/BlhdpUMYxagx2OYc
https://discordapp.com/gifts/DTFhwbnlJO5assQO
https://discordapp.com/gifts/QvdZeiGsOV1amUIV
https://discordapp.com/gifts/SI06yJxWaJ6hASBL
https://discordapp.com/gifts/F33SwrRFzEQAb8dl
https://discordapp.com/gifts/V5vQEJ80xLCAYlsz
https://discordapp.com/gifts/kiZSAAupy0QJMtNU
https://discordapp.com/gifts/wE0V06FQXYVbkdxE
https://discordapp.com/gifts/7ZqQeF9DCg821ywU
https://discordapp.com/gifts/emz8eXpaY3dHMgBt
https://discordapp.com/gifts/2kIIgQ6RwDmo05R0
https://discordapp.com/gifts/YBbMxjsfnfrBgkVA
https://discordapp.com/gifts/EwPfUyfQNwheF21R
https://discordapp.com/gifts/drUA4UvVZScPfigc
https://discordapp.com/gifts/dbdVnttAXmC7mU9o
https://discordapp.com/gifts/PG5NnsiIwPn7smLF
https://discordapp.com/gifts/KiOTIeOXW5jFL58N
https://discordapp.com/gifts/xq7vdse5fJsIhLOT
https://discordapp.com/gifts/D2vhb5PFGTSZxcUC
https://discordapp.com/gifts/Rh3tA6MrEVjDWz6b
https://discordapp.com/gifts/c9t7mjKd4ihrENCD
https://discordapp.com/gifts/LcAsxtQEl2lHHWjj
https://discordapp.com/gifts/HlpaTpDTlwHh6mDZ
https://discordapp.com/gifts/SdZkUncDSdx3fuXH
https://discordapp.com/gifts/fzGyW9dV72gjTFqW
https://discordapp.com/gifts/jAWwXZJQcyK9krfq
https://discordapp.com/gifts/LsUjzxomDKcrH41j
https://discordapp.com/gifts/gi5qGvvIiyVlvYDy
https://discordapp.com/gifts/iWtcyf5VYDu5080B
https://discordapp.com/gifts/EhLNQecDNKCfBP8V
https://discordapp.com/gifts/SqOLWGXaOf6HlNy9
https://discordapp.com/gifts/FAyJhFf9HTW10sbK
https://discordapp.com/gifts/rLDqXQ28gGfVO2aJ
https://discordapp.com/gifts/4VkW3fBRyiTZJqVO
https://discordapp.com/gifts/LOLZqAZyLUm7wi8b
https://discordapp.com/gifts/j46D6OgDVtBYp3YH
https://discordapp.com/gifts/BeVlo1AXaYN1sx71
https://discordapp.com/gifts/ryBtIKmMQ5qAZnnu
https://discordapp.com/gifts/QGreYu2jOfvrzmeh
https://discordapp.com/gifts/I1BAvSbVBII4fZlj
https://discordapp.com/gifts/nL4tpV5TQKjvxZ3A
https://discordapp.com/gifts/coGat2ur7BxwN6Cs
https://discordapp.com/gifts/pvq08hXAvQCrb5Rv
https://discordapp.com/gifts/kL8Kas60w6mvH5P8
https://discordapp.com/gifts/n88ppIuL2liiSzby
https://discordapp.com/gifts/lYwF9TTG8EPcPUlu
https://discordapp.com/gifts/e60oJuqV5aefyIo8
https://discordapp.com/gifts/5W0KC6NNz21WlB6l
https://discordapp.com/gifts/aqizhDhgJnketf0b
https://discordapp.com/gifts/h4LENTmjbAfPBHP3
https://discordapp.com/gifts/p3uen092dxfKfQDR
https://discordapp.com/gifts/fRs3K6uzx4vrR11C
https://discordapp.com/gifts/pUBvmAxHFO60tvFH
https://discordapp.com/gifts/xqX2KqjMEFPoHWvk
https://discordapp.com/gifts/aPOd2dxiBAYvYQ6R
https://discordapp.com/gifts/Gt8CFuNNgxGFoz0F
https://discordapp.com/gifts/n8MweDP4RfVT1dbf
https://discordapp.com/gifts/p9Xf3B95QdLCeLGg
https://discordapp.com/gifts/68x9XtgnI9N2KvvR
https://discordapp.com/gifts/t9P2g7kjTjG1TRMY
https://discordapp.com/gifts/E3AzTANDqnSrtWpN
https://discordapp.com/gifts/zOcOgSGd1kHMzuvD
https://discordapp.com/gifts/SC4vbYBlYsaz9TcS
https://discordapp.com/gifts/XixD8CxoE0u94qYW
https://discordapp.com/gifts/ZIXtRRkDmGNKH8S9
https://discordapp.com/gifts/K6xzyjA8ijPOwH6T
https://discordapp.com/gifts/NHxFRBNSfGN90r9q
https://discordapp.com/gifts/HEmt31RtjAg2uqdL
https://discordapp.com/gifts/1w36EIyvbT85hCFv
https://discordapp.com/gifts/BSKUyGKzRXuYKe3Z
https://discordapp.com/gifts/SikXb7L6tTnByG0i
https://discordapp.com/gifts/l3v4KQLxXibLWsZA
https://discordapp.com/gifts/qaZVSf2job4nOedA
https://discordapp.com/gifts/tOyP6OR31vHSBsrR
https://discordapp.com/gifts/snftclJ2EZprOKmR
https://discordapp.com/gifts/pGyyasKhAAQlDGvh
https://discordapp.com/gifts/JJOlLbrAODy1Oj8D
https://discordapp.com/gifts/TSDk4Yf50qm6rzxH
https://discordapp.com/gifts/4UZlj0d5JYaGjaYL
https://discordapp.com/gifts/eJaWUtUsh01ZEC4b
https://discordapp.com/gifts/Z8euQpRZKiRSa3If
https://discordapp.com/gifts/o3UMvzbskkGqAses
https://discordapp.com/gifts/QmVO2rlTqhD8HIFC
https://discordapp.com/gifts/UozlSvcuUH8xFPTL
https://discordapp.com/gifts/YI3PJ3eKDRq5CKjH
https://discordapp.com/gifts/e934RP5jreISmfrb
https://discordapp.com/gifts/j7NeNWoTmi0wIX4W
https://discordapp.com/gifts/TQ5gvfHE3M64qX2P
https://discordapp.com/gifts/5l6H30wLcv19b9cq
https://discordapp.com/gifts/pwkaSYsY6hb6Ehh9
https://discordapp.com/gifts/kpVOmymUPWbKFb8G
https://discordapp.com/gifts/TcGqdM2eTUzDMU7N
https://discordapp.com/gifts/tMbG20c1YiDoS0Ge
https://discordapp.com/gifts/sCN7ZGaUbbgX8frH
https://discordapp.com/gifts/NZS4De525PBF8rRt
https://discordapp.com/gifts/PvOqd6lwr6AKjnXA
https://discordapp.com/gifts/C2umnE9wpSbTxzDt
https://discordapp.com/gifts/ibAq3KuAsUaFRFJV
https://discordapp.com/gifts/I9MI7xhkDS5x3rvc
https://discordapp.com/gifts/4CpEOsxsJ7HHNHG3
https://discordapp.com/gifts/5ppgXwVgl8XHCqnw
https://discordapp.com/gifts/SUsJackLy2mVKby6
https://discordapp.com/gifts/U9wnzUXa4TS4L6xT
https://discordapp.com/gifts/p5Zd0UzULO5n8WXm
https://discordapp.com/gifts/1Vo3EUh7IuyneqZy
https://discordapp.com/gifts/tc2FBYoU21YXFDwH
https://discordapp.com/gifts/6zZVgs2HJwHyNKSz
https://discordapp.com/gifts/iR8mkjdPH7uUQej8
https://discordapp.com/gifts/hy1rqfsMySGMOrNY
https://discordapp.com/gifts/vfhdzOaQ1kYPBeIB
https://discordapp.com/gifts/h5wErZdcFP82Q3BF
https://discordapp.com/gifts/WTl5Dsgsx9SZddYd
https://discordapp.com/gifts/XvnpNweBFzbjJUyi
https://discordapp.com/gifts/OmmZbiIMvTM64LH4
https://discordapp.com/gifts/g1YfPudGhbESNBoJ
https://discordapp.com/gifts/WbwPVDA7MtxFe7w0
https://discordapp.com/gifts/exLiYMz02HyHXxoI
https://discordapp.com/gifts/8izTlyX6YtvX88XX
https://discordapp.com/gifts/3eOVWsKyXzBnx2eI
https://discordapp.com/gifts/OYyTTFE3xMWyGEXZ
https://discordapp.com/gifts/iZvz5HC7NZyq39HY
https://discordapp.com/gifts/zBjvGvxGHHbnS3fE
https://discordapp.com/gifts/IxHooIozG7dLYw5M
https://discordapp.com/gifts/wm7ZwROhJvCiQvLQ
https://discordapp.com/gifts/2hDpqdCcq9A0ugiB
https://discordapp.com/gifts/m1spc0KNYBvqXAtH
https://discordapp.com/gifts/dhjZkPl4lenkg5uO
https://discordapp.com/gifts/VDM6hRtl57n9rSnb
https://discordapp.com/gifts/Io58zGL5BaRFu0Je
https://discordapp.com/gifts/31kZweYa9VSYP5PS
https://discordapp.com/gifts/sjWFEcPLwTfTtX43
https://discordapp.com/gifts/GRM9g0DS9FrXfnCV
https://discordapp.com/gifts/Y9az7OFm2tDoje5H
https://discordapp.com/gifts/QtPatN7I8G6ppHqD
https://discordapp.com/gifts/iaOyJf4WIlhmYIN4
https://discordapp.com/gifts/yem3ayZ9VWFkpyBX
https://discordapp.com/gifts/ZdynadKMrpjn37Tc
https://discordapp.com/gifts/xfH7cYZTOW05kNwp
https://discordapp.com/gifts/apcjNnRn8uUUs2RN
https://discordapp.com/gifts/ktIQ3BOHEhWGaWku
https://discordapp.com/gifts/iCy12mWuHRaa8s5X
https://discordapp.com/gifts/MSMnJfw4pNV61dVi
https://discordapp.com/gifts/7f8kG0FY8o2EhvPQ
https://discordapp.com/gifts/WQUHvdcX1P4mZ65Z
https://discordapp.com/gifts/0gHazxeXyiwDJZWx
https://discordapp.com/gifts/4VoiquGr0xeUvYcD
https://discordapp.com/gifts/FYq8LNkNFswi5qt6
https://discordapp.com/gifts/2hqRUbNaJoDwJKiw
https://discordapp.com/gifts/IwJ8rwpEx8YJpwgw
https://discordapp.com/gifts/rFFC5l3f4VrLXXTo
https://discordapp.com/gifts/xw1ca0KUDvTUz8B0
https://discordapp.com/gifts/4h2HCJ4aTl2khXq9
https://discordapp.com/gifts/VtKxCkomA04rzeZW
https://discordapp.com/gifts/B0fIhyUHLSqnC2BI
https://discordapp.com/gifts/gQsu3haaoLFYFweO
https://discordapp.com/gifts/tXm0bjNxKcAfXmLy
https://discordapp.com/gifts/WseZVR6tsDKJNXKY
https://discordapp.com/gifts/cNq3G3GpkBKKJOt0
https://discordapp.com/gifts/Q1hrtbwKoY3XRNuH
https://discordapp.com/gifts/0HsVHGN4fRc4AkBy
https://discordapp.com/gifts/Mk9r47KfhTyMyYm1
https://discordapp.com/gifts/AX0Zrdas93RthBIH
https://discordapp.com/gifts/xiDNwLEpdv7MutFg
https://discordapp.com/gifts/Q9r3eTNOFvAek4aY
https://discordapp.com/gifts/nSUqwqa7Nu6ZvBIq
https://discordapp.com/gifts/DFqY531ezCXZMMvQ
https://discordapp.com/gifts/SY3BtTDw7Ek71NZZ
https://discordapp.com/gifts/pFc6iZFxe5seQvr1
https://discordapp.com/gifts/webbJNBrSMw2ueS9
https://discordapp.com/gifts/Tt9luKDtUoKoWhZA
https://discordapp.com/gifts/NCQY5Yd5pMNtSXqI
https://discordapp.com/gifts/DFU5YaQCxURkYOEi
https://discordapp.com/gifts/xvRJvGNcGn3ZLQ14
https://discordapp.com/gifts/mmrkx2JC9nOM5AX5
https://discordapp.com/gifts/jEwj8eHsfvoz53N0
https://discordapp.com/gifts/PBJJRJdmfVbip4Fy
https://discordapp.com/gifts/vQIBCKJCkjgQkKUW
https://discordapp.com/gifts/4YIXGfT8ShMPudko
https://discordapp.com/gifts/L9eZ7PY5du2976aH
https://discordapp.com/gifts/CsMJdNQmCZKlTUEn
https://discordapp.com/gifts/N169EfHjesLSbC9J
https://discordapp.com/gifts/kBpRkfJxo8yRpP1O
https://discordapp.com/gifts/bohUnAamqQldXoF5
https://discordapp.com/gifts/FX2lAMk99o0D9c3z
https://discordapp.com/gifts/4oKpsH4ltnOfcrR5
https://discordapp.com/gifts/dUHf3S8PmOtuS5eu
https://discordapp.com/gifts/9fxAGFgEtrBMQnLy
https://discordapp.com/gifts/hrE39xu3xhImElw2
https://discordapp.com/gifts/8iCBIRP2I9agitGl
https://discordapp.com/gifts/QRYGYDPe8SrsdcGy
https://discordapp.com/gifts/Hq9onxbrj7eWNIwQ
https://discordapp.com/gifts/8xRmDbrkh6Qxo4lm
https://discordapp.com/gifts/HZQ4fg6p2oeZ29SE
https://discordapp.com/gifts/QfXMxdNXYM3XTaQu
https://discordapp.com/gifts/Ndien3BzbiUMaHpH
https://discordapp.com/gifts/mOvmWEWw3ZUIXGpG
https://discordapp.com/gifts/YbCpm5f95oa6OzRP
https://discordapp.com/gifts/5Vep6az6Lvaus0z1
https://discordapp.com/gifts/NwAv6ewM5FTjY449
https://discordapp.com/gifts/yhBbXCsFQAXw7qRW
https://discordapp.com/gifts/0Esvx40K4EL2ZXwS
https://discordapp.com/gifts/CLqHyRuWtdMkxgx8
https://discordapp.com/gifts/dszADhLC0VlS9BLX
https://discordapp.com/gifts/XdXB0dqP4pJSmgeM
https://discordapp.com/gifts/9tHYheTkU9p3W52V
https://discordapp.com/gifts/C4DmefchbbbYmRdN
https://discordapp.com/gifts/qS3R21hkIKOcZgk8
https://discordapp.com/gifts/mB96DK7ZlI1YeQCd
https://discordapp.com/gifts/dTCvFm5i4zqSfafK
https://discordapp.com/gifts/yHD99nWccana4E1N
https://discordapp.com/gifts/u7zZeAe7GSDLN4rw
https://discordapp.com/gifts/ERcAikEkYkN27C7z
https://discordapp.com/gifts/zWV0pH7P6PoNMspP
https://discordapp.com/gifts/6L55VwniAXqrb9EA
https://discordapp.com/gifts/AcTditpg8wuErXp6
https://discordapp.com/gifts/N5mXRr8UHWZvxmDw
https://discordapp.com/gifts/KJ8rvYUJEZpXGbvm
https://discordapp.com/gifts/uyRpXjiisDvlJDAz
https://discordapp.com/gifts/cD3cyRu6tSvUREGR
https://discordapp.com/gifts/ktYnsRBsmO2EFl5N
https://discordapp.com/gifts/q1Wb0hZUOxMPiTsW
https://discordapp.com/gifts/IkRcK12qJPRFqQoy
https://discordapp.com/gifts/e6wR23DURc21wW08
https://discordapp.com/gifts/Sbnu296HXmUn1f0t
https://discordapp.com/gifts/iAun0E5GS6TVM9m7
https://discordapp.com/gifts/566AynObsqCGCsh7
https://discordapp.com/gifts/utXAZo8hMf3ZbrDo
https://discordapp.com/gifts/Mql4BaYySRbjgifI
https://discordapp.com/gifts/9F5Hn7dX5HBDRtvt
https://discordapp.com/gifts/J7soPymnMDg1Ls1D
https://discordapp.com/gifts/6xKjEo3cHEdPUzFy
https://discordapp.com/gifts/0h7sQ7svqUPekMa1
https://discordapp.com/gifts/1WU1RhZyuWUHEknR
https://discordapp.com/gifts/xDMWEfz0KpbAu13y
https://discordapp.com/gifts/EvWni8YqCnMbvD7k
https://discordapp.com/gifts/irns7upG1Idb7HvC
https://discordapp.com/gifts/KlQOFJL7THCa13Lm
https://discordapp.com/gifts/qOCoxkWImxi1ADqN
https://discordapp.com/gifts/MS3HtSnJkJtlCpGF
https://discordapp.com/gifts/j55ZpFgOrlPig20w
https://discordapp.com/gifts/DKZSwjgjkEFLjwhm
https://discordapp.com/gifts/La9gvLF7qELlOptn
https://discordapp.com/gifts/SkeQ9iW6FYv3wBKu
https://discordapp.com/gifts/YUA45bknFVFYqwew
https://discordapp.com/gifts/TNsQIpBKhaPSTqoO
https://discordapp.com/gifts/z7KZmeCidBrWwOOg
https://discordapp.com/gifts/CToRVPFol2QkA1Tb
https://discordapp.com/gifts/IQemrz73gEli12Jp
https://discordapp.com/gifts/UYJGfT6zacIEGav8
https://discordapp.com/gifts/60Gz5inmHzXF7ego
https://discordapp.com/gifts/7U3R7HE40gI7eHpm
https://discordapp.com/gifts/3i7ChpCB4PRXTkX0
https://discordapp.com/gifts/6X48bhvW0kXqFrYO
https://discordapp.com/gifts/hjVyiQwFT56OFZNY
https://discordapp.com/gifts/M3wKj2uJ2zoKNRKb
https://discordapp.com/gifts/VRMPuGwszzVynztM
https://discordapp.com/gifts/em0NuVITRt07Lxmb
https://discordapp.com/gifts/MOHPuJha9tCgHBkk
https://discordapp.com/gifts/Ao9ahpRffTUNikyr
https://discordapp.com/gifts/VwQmGX9PUGl3wRlI
https://discordapp.com/gifts/eqAhbgE9KSTduLOD
https://discordapp.com/gifts/CcY1005IgARn92rz
https://discordapp.com/gifts/c58cenW2NLVDa0RM
https://discordapp.com/gifts/vRxyB5THo9MIQXdF
https://discordapp.com/gifts/F1lyisnZUH6CWQ1T
https://discordapp.com/gifts/BN30amws683mcjsF
https://discordapp.com/gifts/iXQ3YznxpNzBcyFe
https://discordapp.com/gifts/AjeqxAXDK9PF57TH
https://discordapp.com/gifts/fxosVe3clgOuNc7A
https://discordapp.com/gifts/MN3YkJsgpTWJj1xk
https://discordapp.com/gifts/YLnMbO5TOeViN8BC
https://discordapp.com/gifts/BsxRMDjSDLNQRrIb
https://discordapp.com/gifts/g9USpQWtoabiyI14
https://discordapp.com/gifts/7EvM9a1meivmiyIc
https://discordapp.com/gifts/xctFyvrOXBNEwetC
https://discordapp.com/gifts/dmAQlosiuXmzVBCf
https://discordapp.com/gifts/bdPDF5wecMB26uHF
https://discordapp.com/gifts/cXegWmTbiPPjXjsL
https://discordapp.com/gifts/KBDjGJ2ttbZjuc4s
https://discordapp.com/gifts/2AEmbJLh2CS1PppX
https://discordapp.com/gifts/TungynE4EGZ6E3gJ
https://discordapp.com/gifts/VUP8zYwdb3ZeqVzi
https://discordapp.com/gifts/ikxJjIZJhajUvbvX
https://discordapp.com/gifts/tM2TC0KAQ2xVVlmN
https://discordapp.com/gifts/7CBrmjHEieWjwdWu
https://discordapp.com/gifts/xetySPV45WKoFrlF
https://discordapp.com/gifts/D5yrUaRiYa9vg5aV
https://discordapp.com/gifts/eYeeR5uED3xvBmDx
https://discordapp.com/gifts/NHiVhlorRuRurm4R
https://discordapp.com/gifts/86DOOvlUQBkYZk8d
https://discordapp.com/gifts/0HKRL6bobs7RZk8K
https://discordapp.com/gifts/rwEpHM3FhV5GTJ9G
https://discordapp.com/gifts/SyztS1Xlgysg63W3
https://discordapp.com/gifts/Z8NwKh3IUEE08WdD
https://discordapp.com/gifts/AwsHEcZLeXa36YkG
https://discordapp.com/gifts/O6I19WcYfs9kCsIq
https://discordapp.com/gifts/VeeyFvPEbVEwdy9f
https://discordapp.com/gifts/Q5jPucQCEdmd1MQl
https://discordapp.com/gifts/VPG62WFeamjmzxWn
https://discordapp.com/gifts/qLOJWgkP2j9yeun1
https://discordapp.com/gifts/bvFhL3OUGdN7s4y8
https://discordapp.com/gifts/tzbn82sgLJMqHI3j
https://discordapp.com/gifts/DicgyXtZ2sbHxEfV
https://discordapp.com/gifts/J7y6rPvLXoCqnXgW
https://discordapp.com/gifts/GAAFNBiWFSaClviP
https://discordapp.com/gifts/sAkfVbf3Jf0AwY8M
https://discordapp.com/gifts/w8ngXOl3sDWIbx8j
https://discordapp.com/gifts/u45Mwwif3dZOONtH
https://discordapp.com/gifts/3XYo4SzmZ2IczycB
https://discordapp.com/gifts/ittAftdpcd1T74lX
https://discordapp.com/gifts/8hRIiMn1DFXpUcMQ
https://discordapp.com/gifts/XhMrwU2LiCfEFKDN
https://discordapp.com/gifts/apBIBk8KjsImoneD
https://discordapp.com/gifts/SogDruuta66dRYAk
https://discordapp.com/gifts/U51UkqRT7Nnubx4Y
https://discordapp.com/gifts/Alhw7CwWwPIxBy0Y
https://discordapp.com/gifts/lGVxyZTDBSbuG8Fb
https://discordapp.com/gifts/g7hkgFPrhbDNqefM
https://discordapp.com/gifts/Fe5xsEc0tntDPlfw
https://discordapp.com/gifts/o18Sh3dgMqAmgibi
https://discordapp.com/gifts/MQzLZ3glAbPNA3dA
https://discordapp.com/gifts/U8xrOkOBKwNhH505
https://discordapp.com/gifts/Vrbct0sPOBxxxSIj
https://discordapp.com/gifts/t0XQTeeACDyCekjf
https://discordapp.com/gifts/UGbMHNneZ5RdA9bi
https://discordapp.com/gifts/t6EEEJPVixn0tntq
https://discordapp.com/gifts/QNIx727AiRgzVZ5d
https://discordapp.com/gifts/vLotgXQetaxgso4d
https://discordapp.com/gifts/5dQitBQBgVWNOzDW
https://discordapp.com/gifts/b6Hmd9BmUs1GakAs
https://discordapp.com/gifts/0McKyERz8yoAQtI9
https://discordapp.com/gifts/xxBbvpRrHnmwjRME
https://discordapp.com/gifts/CfkOyd6FLufEXG2V
https://discordapp.com/gifts/3nxHp8XAO3yOP5l3
https://discordapp.com/gifts/WoHKhXqapxsdQrj7
https://discordapp.com/gifts/jorKSAU3BO2cALDq
https://discordapp.com/gifts/W07x2Sijt7L80ChR
https://discordapp.com/gifts/pwDhdCrxzNqrh6HQ
https://discordapp.com/gifts/GQyeEqCyuAwQCPXE
https://discordapp.com/gifts/0t5qGqtWp1CpS7ob
https://discordapp.com/gifts/7f3jjEBnCfTnIz4W
https://discordapp.com/gifts/P7HJivCHwJNqokAX
https://discordapp.com/gifts/TTpUPrlei1d6yitg
https://discordapp.com/gifts/DUISdUc8zDJMNJkl
https://discordapp.com/gifts/CVAluJdbORhyTdyf
https://discordapp.com/gifts/iyAjsoxPtbVoSQ6u
https://discordapp.com/gifts/Kqzg5PUUJemu3qgB
https://discordapp.com/gifts/XOyZLGQi6jitogRe
https://discordapp.com/gifts/HblQtSTMS9WYZ8kl
https://discordapp.com/gifts/ILChsJQS6cLToSEz
https://discordapp.com/gifts/KbdjiT4x7lSKu8gm
https://discordapp.com/gifts/Ry0NvuCrNpnjru46
https://discordapp.com/gifts/W3xK8mexxxgKy6Kt
https://discordapp.com/gifts/U8zA86EokIdcZsZV
https://discordapp.com/gifts/1LJa61wgo6K6MBBw
https://discordapp.com/gifts/8e3OoKI0ihE1GRXP
https://discordapp.com/gifts/8UTlVOLpMKK4ty2o
https://discordapp.com/gifts/rRcaYll2lW8z67R9
https://discordapp.com/gifts/QoTLrdB55zBcxJgT
https://discordapp.com/gifts/ahbe5kWQ0xqB67Ry
https://discordapp.com/gifts/xVZDLPo3lBUOdpnI
https://discordapp.com/gifts/xlFoU7AP2sY2tY5o
https://discordapp.com/gifts/hJqEOcmJBd45tRxi
https://discordapp.com/gifts/TkoPyCUk3pE4FP73
https://discordapp.com/gifts/h8JJHF0t2zg69OPR
https://discordapp.com/gifts/VSs3JJjo5103rRcl
https://discordapp.com/gifts/KNoU2sAtUk0Mzzzt
https://discordapp.com/gifts/62Yarin8AmY43jJn
https://discordapp.com/gifts/HuwojOCNplUli1Iv
https://discordapp.com/gifts/uJABXoEPOfWHBi2N
https://discordapp.com/gifts/ZBteSRrqbvOQCfQT
https://discordapp.com/gifts/7WnzdwbjfaQBgHp5
https://discordapp.com/gifts/IKJsPPIJErmORmxX
https://discordapp.com/gifts/s35A4oif0UA76xbm
https://discordapp.com/gifts/jL2fNd5zeTpYh3j7
https://discordapp.com/gifts/8smtcIfn0zVKr0Xb
https://discordapp.com/gifts/z8mynlHyG5oj4bID
https://discordapp.com/gifts/wtHvX6BE9anQdFu4
https://discordapp.com/gifts/NLwUZaliw9LZZznG
https://discordapp.com/gifts/jx60up1A6Rwfi50D
https://discordapp.com/gifts/O8rNAZf2Bae963Vb
https://discordapp.com/gifts/dJ1eQzjE4qxmmzCG
https://discordapp.com/gifts/PY4Ce1XQDvfzG57j
https://discordapp.com/gifts/E74K2RayL63oP9RQ
https://discordapp.com/gifts/Asizs6zSK1chutAe
https://discordapp.com/gifts/zV0AxJEtf5y1sznn
https://discordapp.com/gifts/j5Dt7j18xLofjEzF
https://discordapp.com/gifts/UlbeVQ5WnNNDNzPf
https://discordapp.com/gifts/NVpygrRys8cktKSA
https://discordapp.com/gifts/Rsmcidy3atzGrhMo
https://discordapp.com/gifts/TrBwZmAwf3gtgsyT
https://discordapp.com/gifts/2dB5P8QHzPpzHgaP
https://discordapp.com/gifts/LiAtxlJ6rPJ7qRxF
https://discordapp.com/gifts/9xZrF3gM0stUTTVC
https://discordapp.com/gifts/dl4LjWU7PNeL1e72
https://discordapp.com/gifts/l2Vy0jGeMWiALLqq
https://discordapp.com/gifts/PaOVDamamCNxVsI9
https://discordapp.com/gifts/zKkaFwMr7EoDW9oq
https://discordapp.com/gifts/J1xDMhDbCSqkKkEa
https://discordapp.com/gifts/hlzoDS6P9I1Madxq
https://discordapp.com/gifts/6qRd1y3rNI8xQzqO
https://discordapp.com/gifts/dEA9f6GAxBY7lG3M
https://discordapp.com/gifts/m4beXvTFFYKyukTX
https://discordapp.com/gifts/8OFrboW4N3gerKcu
https://discordapp.com/gifts/VHK1Lu6VYwobOFpr
https://discordapp.com/gifts/4fRALw8kpU9iTnqJ
https://discordapp.com/gifts/cnWr9QHV5bh5o6iL
https://discordapp.com/gifts/z4ZSArI7e5a883EP
https://discordapp.com/gifts/BRFqrwjbDKq0Plja
https://discordapp.com/gifts/nCFt7ysWOODGkrZG
https://discordapp.com/gifts/ryJUXrAVm4RvdReG
https://discordapp.com/gifts/ThJZQarCiQO87RGM
https://discordapp.com/gifts/MLJh5hvy9jKHee2A
https://discordapp.com/gifts/lE06zW2giWf7sXEK
https://discordapp.com/gifts/VU86LrWuVo6ptwPZ
https://discordapp.com/gifts/b6WRkvM1cTcGJZ5x
https://discordapp.com/gifts/HiEl0YgtmCvQi4OP
https://discordapp.com/gifts/dp2frRNfeUU48qrY
https://discordapp.com/gifts/i8BMRwLKUrSpps2L
https://discordapp.com/gifts/L5MhOrGbL36dOXqq
https://discordapp.com/gifts/uoFdkcxoVoo3O1JA
https://discordapp.com/gifts/BpIlK6sVbNUg0tya
https://discordapp.com/gifts/ufI9b4NAdvtKy2YD
https://discordapp.com/gifts/ECimXZ5S5rGmahnB
https://discordapp.com/gifts/YCiEDhx5PvlHMTTf
https://discordapp.com/gifts/qfV034Eu6iVvTfJV
https://discordapp.com/gifts/akrnydodRLnhl3z6
https://discordapp.com/gifts/FgnLRXvcm7VtIANB
https://discordapp.com/gifts/ijpGKHHjc8vyJix7
https://discordapp.com/gifts/2OvkI7YPLDktnM05
https://discordapp.com/gifts/dbGmJfFSC8aHn24l
https://discordapp.com/gifts/OjMJGFQ1J5Is8Uuf
https://discordapp.com/gifts/1XBEeWaiMNfFZ7DF
https://discordapp.com/gifts/buSUyjF0q8IMm9Fg
https://discordapp.com/gifts/goln6MOpbieWOYzw
https://discordapp.com/gifts/SBRN1HAJru6rb60Y
https://discordapp.com/gifts/H5SzyOfT0wL2bqFB
https://discordapp.com/gifts/jSOqisBCXB8jRGG0
https://discordapp.com/gifts/dDi2eg6fjreuDIgf
https://discordapp.com/gifts/H9rQzBUHEwpLKdid
https://discordapp.com/gifts/eJohuZZaS9s9vHTS
https://discordapp.com/gifts/6SS0oo02yk7uEixE
https://discordapp.com/gifts/piLwmmClOlsJo0Nq
https://discordapp.com/gifts/Y9e1H2NCsU98lola
https://discordapp.com/gifts/ClOwyrCRaBFR7Rz9
https://discordapp.com/gifts/oldaIRHIhykKkDkc
https://discordapp.com/gifts/x2Vt9uTjrwey3Zz1
https://discordapp.com/gifts/9GXqSf2eWuSMmQsc
https://discordapp.com/gifts/jf5Vee2fYDmGBCZP
https://discordapp.com/gifts/Nq1RCl7GsEJRoz7u
https://discordapp.com/gifts/yZvTd5TY9WodL21a
https://discordapp.com/gifts/lwKS6YaJwl4yXOqA
https://discordapp.com/gifts/Ow5eN1rHFZOAbwaW
https://discordapp.com/gifts/iveGT7SkRUuGWWW8
https://discordapp.com/gifts/txwKMtNPVoFjR8du
https://discordapp.com/gifts/ksdLpnGTYEH3jMFs
https://discordapp.com/gifts/jGLoea4jjH9G23tJ
https://discordapp.com/gifts/RszqOPEFHXJnZXGM
https://discordapp.com/gifts/54Py5Sw5NqUcyylq
https://discordapp.com/gifts/cIowwWfouPS8Wdr5
https://discordapp.com/gifts/MMh8uBK4Nm6uMCFJ
https://discordapp.com/gifts/Q37nZBtRwGF016zu
https://discordapp.com/gifts/zbcZoDoTjdT2hx1J
https://discordapp.com/gifts/YQNQisjAnujrn2MT
https://discordapp.com/gifts/osbxTIqOCEEszDyG
https://discordapp.com/gifts/hJyaquNGaKzXR3H6
https://discordapp.com/gifts/pPsx6exPGA8sFPzG
https://discordapp.com/gifts/6vWQNORfVhFKaegg
https://discordapp.com/gifts/4BAVtOSFhd8f8hrs
https://discordapp.com/gifts/nqZZ7Yv9UDrs4ycX
https://discordapp.com/gifts/MYLKC89FOYRVgXl8
https://discordapp.com/gifts/s86LrabDTbxoRr4J
https://discordapp.com/gifts/KX8YKbUAoybHQDfs
https://discordapp.com/gifts/r6F16G1FYUCR0loQ
https://discordapp.com/gifts/UvD4kYvtmCl7oqa2
https://discordapp.com/gifts/qWbNs3GtqoDupQo1
https://discordapp.com/gifts/W3Sz5rNhywDewL6V
https://discordapp.com/gifts/p2lmuxmj6rLrNeTv
https://discordapp.com/gifts/EDjCdkT4oucwOAc9
https://discordapp.com/gifts/Esc4kzfQmWioTCAP
https://discordapp.com/gifts/icX0Rx09yVb5rWzY
https://discordapp.com/gifts/7iEgII9IkueyIuLq
https://discordapp.com/gifts/25BXWvLLpdGwP4xX
https://discordapp.com/gifts/1aS7SNQ1Oe5HWPI0
https://discordapp.com/gifts/TYoegz78W59mPq3Z
https://discordapp.com/gifts/qkrJpvfsGwkaSnaQ
https://discordapp.com/gifts/zLfxw7JfRd96HM4z
https://discordapp.com/gifts/EscY9AQ94mNN6nUr
https://discordapp.com/gifts/9Rm97249Zeu0xScQ
https://discordapp.com/gifts/h5RfHBtoAJwojDn2
https://discordapp.com/gifts/DOUSGRl7y2h49kWY
https://discordapp.com/gifts/D0gWOkNbl0qMpdhr
https://discordapp.com/gifts/f3Y2QF3TYvW8U21x
https://discordapp.com/gifts/xlNl81WgrynDlBIk
https://discordapp.com/gifts/HoPIVVfsC433SgQJ
https://discordapp.com/gifts/F7kawe3PzDJJ78yp
https://discordapp.com/gifts/TdbVfBKNU1YU8oom
https://discordapp.com/gifts/Rj6yVZ2Vueifx1pz
https://discordapp.com/gifts/tgyOFK36fLZMl8fN
https://discordapp.com/gifts/07ow3E9Vj4PX255H
https://discordapp.com/gifts/IIGChLHuj4tm7P3F
https://discordapp.com/gifts/ZXmSjF2CiqzSQCIp
https://discordapp.com/gifts/UKMVBXpaxts7OslM
https://discordapp.com/gifts/t4MC1QGvA4CYBLYi
https://discordapp.com/gifts/g54pVqupk34MPdCJ
https://discordapp.com/gifts/7cKFvsgKbyF7q6wP
https://discordapp.com/gifts/ewGBEbKSd9nWHKdS
https://discordapp.com/gifts/00kokOHMul05ixNM
https://discordapp.com/gifts/3Tvop5f4fzIoPois
https://discordapp.com/gifts/Sl3Qse5PwtKEEmLY
https://discordapp.com/gifts/bGWBDrFcGA513qBV
https://discordapp.com/gifts/Uw2UpHFUTxwULDSo
https://discordapp.com/gifts/idoVFI0nZ6pF27iq
https://discordapp.com/gifts/POVbq5Ut97TVuMSg
https://discordapp.com/gifts/GVLMXjh4PLwGQpiJ
https://discordapp.com/gifts/JrBGXinjqkJaoA0x
https://discordapp.com/gifts/cIQqq4sW9yhQ047L
https://discordapp.com/gifts/xEUsnopkcuSFltqW
https://discordapp.com/gifts/4drWeEv4rnL4ybBS
https://discordapp.com/gifts/qTrsUB1z9QRiBOFr
https://discordapp.com/gifts/CMbZ4AJX0svzIWa8
https://discordapp.com/gifts/XmXFPUmiuTGvyMo1
https://discordapp.com/gifts/szkn6vb8VOxiMJns
https://discordapp.com/gifts/1hKtV6XKwZkXj610
https://discordapp.com/gifts/PsHGcJwG0HYnnSaQ
https://discordapp.com/gifts/ptOyEwoOrC74c4IE
https://discordapp.com/gifts/fk2w8k496dM2gf4x
https://discordapp.com/gifts/JyllUnSPEEwmM9O1
https://discordapp.com/gifts/8Bd0VUDPcTx8nC29
https://discordapp.com/gifts/hmvyHyrqA81WTBBQ
https://discordapp.com/gifts/ny0ylDazS34WUq5v
https://discordapp.com/gifts/zjpHq65Az7yiV88x
https://discordapp.com/gifts/PPxQZ5gY94GYQ47X
https://discordapp.com/gifts/p3UdPUg3wcoKZ8o9
https://discordapp.com/gifts/bNjkWQOiBpmEhi97
https://discordapp.com/gifts/wN7CkrXgmjO6NicM
https://discordapp.com/gifts/nHkEa3nhj7OsgZuD
https://discordapp.com/gifts/OLD6oeqozR4lA37i
https://discordapp.com/gifts/D9yj263k08f3NooB
https://discordapp.com/gifts/qUlWz3jgPSmlahZ4
https://discordapp.com/gifts/GA7WFLzLE1D5TlDJ
https://discordapp.com/gifts/NteVswwbNDhXJbkj
https://discordapp.com/gifts/1bOUywF8JVjmGIEw
https://discordapp.com/gifts/YomLGNt4vMgdqkQx
https://discordapp.com/gifts/rSuodMJ7iL3NwFUp
https://discordapp.com/gifts/sOHjrBHxGVVBi3rv
https://discordapp.com/gifts/wQhJg8SuDWKt9fpJ
https://discordapp.com/gifts/L0vxajkfrBPXbLyD
https://discordapp.com/gifts/E3mr6P7I4GIuPTSY
https://discordapp.com/gifts/m3fMMuyDiCIwdrgv
https://discordapp.com/gifts/kl5jRaxWIxpT2biJ
https://discordapp.com/gifts/al7bjgbyiX9DUIIP
https://discordapp.com/gifts/wIrxdspoJZPyMnj3
https://discordapp.com/gifts/v9NlaSXl1Zpat2G9
https://discordapp.com/gifts/LC0wtTxgo3TJ5umX
https://discordapp.com/gifts/hrG1aKebKPzfnaXC
https://discordapp.com/gifts/NtBOCN3m6e6N15Hd
https://discordapp.com/gifts/BNf9fF6fu7Rw5fwq
https://discordapp.com/gifts/vbwgp5S0Lq2pOSbJ
https://discordapp.com/gifts/OmBn7fRWFHOk7OzD
https://discordapp.com/gifts/pqqPeuj4Xitc5GJa
https://discordapp.com/gifts/1kAWfHVR3w7EO17I
https://discordapp.com/gifts/VZw5vDu5GrmlQTW0
https://discordapp.com/gifts/rapsArFAJ3edK8Mw
https://discordapp.com/gifts/oHssDBqiMKK6eTTc
https://discordapp.com/gifts/RAWRDalzIlIZYUU2
https://discordapp.com/gifts/ItiTXY9sEyE1Y3M0
https://discordapp.com/gifts/jG8QrVmJg4ayZoHc
https://discordapp.com/gifts/9dGaNWa6qzPyo2JP
https://discordapp.com/gifts/SA1ZVlaJof9eHLQ9
https://discordapp.com/gifts/rm32XG34lvJH6cRo
https://discordapp.com/gifts/bkZfFLmghfGio5iy
https://discordapp.com/gifts/ne6j5lNgoxNuxHLt
https://discordapp.com/gifts/WYrkW6YqSgvhitcE
https://discordapp.com/gifts/PORRRQJgOxq30GNY
https://discordapp.com/gifts/C8rHaxh3Zu5pNnbJ
https://discordapp.com/gifts/JGhwoA8XVGujF2Pj
https://discordapp.com/gifts/HIF9Nygv83txB6D9
https://discordapp.com/gifts/4GZuZBnH2PJoV0LA
https://discordapp.com/gifts/dnqjG44EWUHeLzRx
https://discordapp.com/gifts/g3HpUtbWOo0adZXF
https://discordapp.com/gifts/dJOLk8uB5gVp15Uf
https://discordapp.com/gifts/x8i6J2Hf8qCa3B6S
https://discordapp.com/gifts/NGXUu6Pu8lD41FWc
https://discordapp.com/gifts/eLQsNSEj98rQXuZY
https://discordapp.com/gifts/3naKJiw3JfHoJkir
https://discordapp.com/gifts/Md67b6VDAaXLNoGN
https://discordapp.com/gifts/cIoxPF6UqEQWV6Q5
https://discordapp.com/gifts/57XEPQJr6nCN8OzN
https://discordapp.com/gifts/Va6Bz8ASD2vd0Lw1
https://discordapp.com/gifts/oa8j3vEZ0RaN0uve
https://discordapp.com/gifts/iKGjzQVvlQfU0e7F
https://discordapp.com/gifts/m1m6qrw8VH26Z1sf
https://discordapp.com/gifts/ejlWCeoDj7qwVXGd
https://discordapp.com/gifts/pP8AeKUPjFlU49b6
https://discordapp.com/gifts/BnRAmWVmNf3tAwzW
https://discordapp.com/gifts/KEwCFmb3rdRfoZmq
https://discordapp.com/gifts/WxrW2m5U00ak3dAd
https://discordapp.com/gifts/0VdZX3ZMnL1gkKJC
https://discordapp.com/gifts/gFW5wtMbcUEBB1ay
https://discordapp.com/gifts/SC4rbEZmil2w2Ovc
https://discordapp.com/gifts/lxmKlmKxBaXi1oOE
https://discordapp.com/gifts/WfFBuvVd9iEb0ix1
https://discordapp.com/gifts/BRzWclVvZjoSa3MR
https://discordapp.com/gifts/akW7fAAxtmZdzd0X
https://discordapp.com/gifts/olBgv0ajirLDHwxH
https://discordapp.com/gifts/Ns7Dr4d187xm2uPn
https://discordapp.com/gifts/IVm2SrY2SfLGMsIg
https://discordapp.com/gifts/Of93reclzWRkmuII
https://discordapp.com/gifts/wz3YmKAlTtj7a3n0
https://discordapp.com/gifts/FDGE9hAN6xZPY6ul
https://discordapp.com/gifts/67WZoUx9Y1xcFmUI
https://discordapp.com/gifts/OXihMe46v77tiys7
https://discordapp.com/gifts/hfKdmuWhIMcLiPAC
https://discordapp.com/gifts/T2IaiyxzSHnZ9BK9
https://discordapp.com/gifts/JJMgJPnfXSumKJOw
https://discordapp.com/gifts/q2Cfw9OOrwOTaSms
https://discordapp.com/gifts/sSQAE5Gg42BNUslt
https://discordapp.com/gifts/8qNXAtfqcFSdC88z
https://discordapp.com/gifts/hcQIpP5GwnR3Ohxy
https://discordapp.com/gifts/QD71NTunH4WyCIWl
https://discordapp.com/gifts/3LemMcMRo9svZA5H
https://discordapp.com/gifts/9ARC8k2VTBp9y9XR
https://discordapp.com/gifts/GyvBlfazbvjra0yc
https://discordapp.com/gifts/9bhEUpDU7Ki8BiHE
https://discordapp.com/gifts/N5xBw1177gFYAUxV
https://discordapp.com/gifts/XsrsSDTLk0vblcSo
https://discordapp.com/gifts/pBwqMBSShQ8U4RbU
https://discordapp.com/gifts/R29FjuzTraBLF6yX
https://discordapp.com/gifts/ctpATUPLka6mClXr
https://discordapp.com/gifts/6T1vQcwQcXVK1OKr
https://discordapp.com/gifts/4iuraBdtUDLEhDMV
https://discordapp.com/gifts/OMdn8FNH2KLfH7pq
https://discordapp.com/gifts/gJp7Hg5I2G5AAyrs
https://discordapp.com/gifts/Gmy8s0w7bpTmRkf8
https://discordapp.com/gifts/Dc1zFglXIdLxEC9m
https://discordapp.com/gifts/4sfzqFuNe1ygyrU3
https://discordapp.com/gifts/wU96DgG2VjvLhR6c
https://discordapp.com/gifts/gAKxtUMg5c2oVEdN
https://discordapp.com/gifts/utNNk2PXeKJCN1cT
https://discordapp.com/gifts/xUTTjoRnlFMjHcC2
https://discordapp.com/gifts/HvdMT5NaWjduLIpN
https://discordapp.com/gifts/T3BYpAQkcDbEaDnu
https://discordapp.com/gifts/V8RCGBHwrz985xTO
https://discordapp.com/gifts/izD0UWmj9kHpTW82
https://discordapp.com/gifts/m3NX9scEiYQtMdgh
https://discordapp.com/gifts/0AO4YCllmnLbkuoD
https://discordapp.com/gifts/73F48A6PlpxDduKc
https://discordapp.com/gifts/Z4o8Xmn5U3qamG59
https://discordapp.com/gifts/rhC3nqGwDxSxOByc
https://discordapp.com/gifts/QnbASbE6GbzvlbMh
https://discordapp.com/gifts/kt0yXqoAVEXZtRXw
https://discordapp.com/gifts/hqLLzcAip83aTIcR
https://discordapp.com/gifts/OVVy1jq4CBdmxxCa
https://discordapp.com/gifts/Bpk8yoxm7KNqdeEj
https://discordapp.com/gifts/f5BfjV6gkywCJQTG
https://discordapp.com/gifts/VWe7Bf1P2fGlD0kB
https://discordapp.com/gifts/xpHsHgiDUL4v557R
https://discordapp.com/gifts/y7bCk7j4P3Sw6Rz1
https://discordapp.com/gifts/Y9WSN0HJyYHxjgzd
https://discordapp.com/gifts/pDcltgRYtU6YBGoL
https://discordapp.com/gifts/OImQz3odd5ZU13e6
https://discordapp.com/gifts/GKiBwy5huoD4u9kj
https://discordapp.com/gifts/rqCxSCgz4pYdnRgc
https://discordapp.com/gifts/BOhTJXayLjPjX83d
https://discordapp.com/gifts/fJvgM2UcIdf23k7V
https://discordapp.com/gifts/phyC2D9Y70dh9dyW
https://discordapp.com/gifts/ytqLW5SQ0ELKdEuK
https://discordapp.com/gifts/S0NdycqjsB2Fq0XA
https://discordapp.com/gifts/jecg9yy83yjO5C0T
https://discordapp.com/gifts/6BCgbDepvPwRJufe
https://discordapp.com/gifts/7w7KtXJrHyFBzUP2
https://discordapp.com/gifts/tVsSfNZyeGqh3iBD
https://discordapp.com/gifts/U4DT2yWFAgrf54s0
https://discordapp.com/gifts/YDcsDOiarV4gklW0
https://discordapp.com/gifts/lp9KRkAE57aqrcge
https://discordapp.com/gifts/0Njd7liorbsEUzTr
https://discordapp.com/gifts/bbIxPE9kQyKazqPZ
https://discordapp.com/gifts/fFQ1eI4JFXzsCWTW
https://discordapp.com/gifts/gWy3eeS2UUcqIMEq
https://discordapp.com/gifts/8XRBv0b8Bu4YIuNZ
https://discordapp.com/gifts/g36FFl0o8A2NFhuO
https://discordapp.com/gifts/eYQDYgHBUZ7yygap
https://discordapp.com/gifts/7fUhelngkNMQnYm3
https://discordapp.com/gifts/IzZkHJ2xUpDb6eoW
https://discordapp.com/gifts/Bo4UK0rGskEYMnmU
https://discordapp.com/gifts/tnPqTAURhQ1aI1Ac
https://discordapp.com/gifts/9cPQ6AVGwBHTWdif
https://discordapp.com/gifts/EIwRLVA67ykDZ7GE
https://discordapp.com/gifts/pH6qxEQH4EwDPwPZ
https://discordapp.com/gifts/BdvULTpUr8cDI81q
https://discordapp.com/gifts/TZnzUs2lQROLT06G
https://discordapp.com/gifts/yQ8h2QPOyqSMJc2a
https://discordapp.com/gifts/hhWmUwonjjJaAGvE
https://discordapp.com/gifts/Gspx5iX0d5MH1GCn
https://discordapp.com/gifts/lMzXl177cgaFFNuv
https://discordapp.com/gifts/wQWg1xMZOs9Zosxb
https://discordapp.com/gifts/zdfGnBKqDrFjOmii
https://discordapp.com/gifts/KgKIlzoJzvxKGpYU
https://discordapp.com/gifts/IyZGNLkYvRoYYMCJ
https://discordapp.com/gifts/DXrlLlM6eemcfddC
https://discordapp.com/gifts/040GW5jjIUcjQowm
https://discordapp.com/gifts/blPSmK9WCVEsMMO1
https://discordapp.com/gifts/zF4D6XJmOTQzwEMw
https://discordapp.com/gifts/lV6El19SUnPvBim3
https://discordapp.com/gifts/1IDSKeuz5khcXruV
https://discordapp.com/gifts/nLKcsZR5BXNYFGhz
https://discordapp.com/gifts/oFCkP2kuATser598
https://discordapp.com/gifts/5DOFmJpfyjlVB2z0
https://discordapp.com/gifts/nxbkLPvLyqcz2KB6
https://discordapp.com/gifts/QrDbjUPpT4BQcTEk
https://discordapp.com/gifts/0irdle9YHZWriDVP
https://discordapp.com/gifts/tUewTh0lSaqJEhn1
https://discordapp.com/gifts/DNGZ4Vl2PucZHQRo
https://discordapp.com/gifts/kKc3apz6J39ZSptL
https://discordapp.com/gifts/JCbpFFQcH6Bi8Stn
https://discordapp.com/gifts/octZsudkUOxnvV6H
https://discordapp.com/gifts/IcoUssYSka1urfjh
https://discordapp.com/gifts/446sAkXshf4jnvll
https://discordapp.com/gifts/Tfpzu6kSv0uQHIJk
https://discordapp.com/gifts/Xxudtwig8960NNRG
https://discordapp.com/gifts/sawp7wMMhi3ZbrdS
https://discordapp.com/gifts/ohCGPJxtV1qZlxsO
https://discordapp.com/gifts/ScARTlb2mvkDzzzm
https://discordapp.com/gifts/Q5VzdvhfrzqaO02C
https://discordapp.com/gifts/sgd7N583wEKjRIxo
https://discordapp.com/gifts/T1pVPNHT1UbRNi9A
https://discordapp.com/gifts/mCyCocUgfgLhR5mN
https://discordapp.com/gifts/ePAQEQUDzRADBrmf
https://discordapp.com/gifts/DanbPOvd6qKAmWdN
https://discordapp.com/gifts/RhVsHKdoB6gX3jtV
https://discordapp.com/gifts/VYCrWo768p98kOK8
https://discordapp.com/gifts/VTTPV8QGJ25ZmszY
https://discordapp.com/gifts/1HdKF7x2GkTPZvMq
https://discordapp.com/gifts/LAsISZUWFZNGhono
https://discordapp.com/gifts/NM5jX6yqPL0RPiFN
https://discordapp.com/gifts/qCLzwISwrV7EmOHo
https://discordapp.com/gifts/FiZkEhy4aub6Culd
https://discordapp.com/gifts/FLLt0QMaghoKJfFi
https://discordapp.com/gifts/C3Iysf6ylUylcNAu
https://discordapp.com/gifts/yWcrOshYbGrYbgl5
https://discordapp.com/gifts/wf3v1TI7iysqEe6K
https://discordapp.com/gifts/Lev1Zvqjcniu7qjI
https://discordapp.com/gifts/BXVwYUI4XpWHaAA9
https://discordapp.com/gifts/pRyVcvK8oZbWJcVR
https://discordapp.com/gifts/UITGPmeh4a4TqnZ7
https://discordapp.com/gifts/ADRbJv0ZTVJ8FHhZ
https://discordapp.com/gifts/4gc4z7tG69etVoAS
https://discordapp.com/gifts/U6PksYbnPH913Iog
https://discordapp.com/gifts/bkttBEjOykzOIrBh
https://discordapp.com/gifts/rZpvPrBW1TjOhhaC
https://discordapp.com/gifts/tL1TOqG0ROZ2hnXy
https://discordapp.com/gifts/eRZLWYD1y9dMSRdL
https://discordapp.com/gifts/hJ2DHYtOFvSBHHSS
https://discordapp.com/gifts/lG8rWJHvoWLxf2dm
https://discordapp.com/gifts/aoQcbFaXP5DR5Lsv
https://discordapp.com/gifts/zSZ0o5Xfr2V1wvWN
https://discordapp.com/gifts/UVspKqzqc4BmaXG4
https://discordapp.com/gifts/DdD4uwPP5e8IQD2E
https://discordapp.com/gifts/WIFfCGXLYqo2eaw9
https://discordapp.com/gifts/XTmLxw511YFVlbUb
https://discordapp.com/gifts/LOBmqcyi7HOdkmfm
https://discordapp.com/gifts/ryPpAXj84IbJ4QLn
https://discordapp.com/gifts/6nZGeDxlAyBpW3Ee
https://discordapp.com/gifts/6qkImiKJT4HAFzup
https://discordapp.com/gifts/ke4rgsfqSkELNR8X
https://discordapp.com/gifts/ZEBDZv7WzRLFCrBQ
https://discordapp.com/gifts/jh98exnb0l6mi1On
https://discordapp.com/gifts/VJjas4c05vBl8q9c
https://discordapp.com/gifts/NZZM0w8eAstHVEHJ
https://discordapp.com/gifts/XdBNYxzDRFyXH6OM
https://discordapp.com/gifts/dWwkq0tVc0NM4Hhm
https://discordapp.com/gifts/u01wr7bfgtzIsE2i
https://discordapp.com/gifts/717mkU85SmUE661n
https://discordapp.com/gifts/t6zVTzFnsy09Vlps
https://discordapp.com/gifts/pEioXaLSxUWY9IPX
https://discordapp.com/gifts/GJkJwz7q2xoQLPR6
https://discordapp.com/gifts/89wC79bxEMMx1lHL
https://discordapp.com/gifts/E82R5yjiVsmCHHEC
https://discordapp.com/gifts/yYDNtIlWkpYctA62
https://discordapp.com/gifts/pGqipptnDxJnKBF4
https://discordapp.com/gifts/7KDtqTtXhR5YQ1PH
https://discordapp.com/gifts/wi39PzDhH3zwNJyu
https://discordapp.com/gifts/cCKwiu1fZW4hZ01Q
https://discordapp.com/gifts/YrmOe9REQYgQXTCU
https://discordapp.com/gifts/bLqcoYWGIvqbpP0e
https://discordapp.com/gifts/mI6dFMpu5k0hP1T7
https://discordapp.com/gifts/mz5WWlMjdVGteUv1
https://discordapp.com/gifts/MswowTlNSvLzroNw
https://discordapp.com/gifts/rW1ExRvGY2fgLxBf
 '))
value = 700
while value <= amount:
    code = "https://discord.gift/" + ('').join(random.choices(string.ascii_letters + string.digits, k=16))
    f = open('Codes.txt', "a+")
    f.write(f'{code}\n')
    f.close()
    print(f'[GENERATED] {code}')
    value += 1
